### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by Tyler887** [learnbyexample/Linux_command_line#1]
I see this project does not have a license. The default is copyright. Consider licensing this project under [an FSF-libre documentatiom license](https://gnu.org/licenses/license-list.en.html#FreeDocumentationLicenses).

**Comment by learnbyexample** [comment]
I do have a license: https://github.com/learnbyexample/Linux_command_line#license

Or did you mean I should add a separate license for code snippets?

**Comment by learnbyexample** [comment]
I'm working on a new version of this book. The CC license remains for the book and I've added MIT license for code snippets.
